### PR TITLE
fix: devtools to patch api.setState

### LINKED ISSUE #171: devtools don't always log
devtools log fine as long as you call `set` (inside the `create` function). However, if you use the `useStore.setState` function to set some state, devtools doesn't log it.

Here is a minimal reproduceable example:

https://codesandbox.io/s/beautiful-ellis-17s7g

The `increase` function logs fine, the `setToFive` function does not.

Judging from the code, I think it is because `namedSet` is kept locally here:

https://github.com/react-spring/zustand/blob/a6417ce460a31cec94adc4a32c55d1abc98a00ba/src/middleware.ts#L54-L63

Currently, the middleware can only return the initialState, but since we want to wrap the setState function, we would somehow need to return / expose that function as well. What do you think?

### PR DESCRIPTION
**Pull request by dai-shi**
Close #171. 

~There are a few technical issues:~
~1. we need to fix types in vanilla.ts and index.ts too.~
~2. we can't chain middleware that only patches `set`.~

~Due to 2), I'm a bit hesitant to this approach.~

### CODE REVIEW

**Comment by dai-shi** [comment]
@TkDodo Here's your example with this change. https://codesandbox.io/s/agitated-stonebraker-bg7bi

**Comment by dai-shi** [comment]
Okay, this f4c6239 should be much better.
https://codesandbox.io/s/wonderful-lovelace-rjego

**Comment by TkDodo** [comment]
Thanks! From what I can tell, the code looks good. I understand that we cannot change the interface of  `set`, so there won't be the possibility to give those "actions" a name, but this is an understandable limitation 👍

**Comment by dai-shi** [comment]
@TkDodo Did you try the sandbox?
It would be nice if you could try and find possible bugs.

> we cannot change the interface of `set`, so there won't be the possibility to give those "actions" a name

By `set`, do you mean the first argument of the creator function, or `api.setState`?

**Comment by TkDodo** [comment]
> Did you try the sandbox?
> It would be nice if you could try and find possible bugs.

Yes, I did try the codesandbox and it works fine for me. I made a test case for testing it in combination with the redux middleware: https://codesandbox.io/s/react-forked-xbjg9

From what I can see, the `INCREASE` action is logged twice (once as `action` and once as `INCREASE`). This is the same as the previous behaviour, so this PR didn't introduce this. However, `setState` is now logged as well (wasn't logged before), so that's good. Is this worth a follow up issue maybe?

> By set, do you mean the first argument of the creator function, or api.setState?

I mean `api.setState`. `set` in the creator function is patched / typed so that we have a third argument "name", but that's not the case for `api.setState`

**Comment by dai-shi** [comment]
Thanks!

> From what I can see, the INCREASE action is logged twice

Maybe, I can fix it in this PR.

> I mean api.setState. set in the creator function is patched / typed so that we have a third argument "name", but that's not the case for api.setState

Yeah, totally correct. Let's leave it as a limitation because types would be too messy, if we were to support this. (I think it's technically possible.)

If you are adventurous, it might be able to do like this:

```js
const useStore = create(devtools((set, get, api) => {
  api.setState = set
  return {
    // ...
  }
}))
```

**Comment by dai-shi** [comment]
https://codesandbox.io/s/react-forked-6czzc
Looks good?

**Comment by TkDodo** [comment]
> Yeah, totally correct. Let's leave it as a limitation because types would be too messy, if we were to support this. (I think it's technically possible.)

yes, sounds good.

> If you are adventurous, it might be able to do like this:

Yes, I am actually doing that already as a workaround until this PR lands:

```
let setState: SetState

const useState = create<State>(
    devtools((set) => {
        setState = set
        return { ... }
}))
```

> Oh, but this will stop logging if you use set with redux middleware.

hm, how would you even do that ? In the example, we only pass the `reducer` to `redux`, and `useState.setState` is now correctly logged ... 🤔

**Comment by dai-shi** [comment]
This 99a9f64 is probably better, even thought it's unlikely that people don't use `set` with redux middleware.

**Comment by dai-shi** [comment]
@TkDodo Would you do the final test? If it's OK, we release it.

**Comment by TkDodo** [comment]
using the `redux` example with 99a9f64 now logs `increase` button twice, first as `setState` and then as `INCREASE`

https://codesandbox.io/s/angry-mestorf-qymx1

**Comment by dai-shi** [comment]
Oops!

**Comment by dai-shi** [comment]
Reverted. 😄 

https://codesandbox.io/s/react-forked-661ih

**Comment by TkDodo** [comment]
👍

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/zustand/v/3.0.3

**Pull request merged**
